name: CI - Quality & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Playwrightブラウザのバージョンを取得
        id: playwright-version
        run: echo "version=$(npx playwright --version | grep -oP '\d+\.\d+\.\d+')" >> $GITHUB_OUTPUT

      - name: Playwrightブラウザをキャッシュ
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Playwrightブラウザをインストール
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Playwrightブラウザの依存関係のみインストール
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: npx playwright install-deps

      - name: 品質チェック (Prettier, ESLint, TypeScript)
        run: npm run quality:check

      - name: ユニットテスト実行 + カバレッジ生成
        run: npm run test:coverage

      - name: カバレッジレポートをCodecovにアップロード
        uses: codecov/codecov-action@v4
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: false

      - name: E2Eテスト実行
        run: npx playwright test

      - name: Playwrightテスト結果をアップロード (失敗時)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
